name: Build & Check Spring Boot

on:
  push:
    branches:
      - main
      - release/**
      - feature/**
      - staging
  pull_request:
    branches:
      - main
      - release/**
      - feature/**
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build & Test
        run: mvn clean verify
